export const API_URL = 'https://a2.techbuzz360.com/demanzo/wp-json/custom/v1/';
export const BASE_URL = 'https://a2.techbuzz360.com/demanzo/';
export const FORM_URL = 'https://a2.techbuzz360.com/demanzo/wp-json/contact-form-7/v1/contact-forms/';
export const NAV_URLS = 'https://a2.techbuzz360.com/demanzo/wp-json/custom/v1/parsed-navigation/';
export const MEDIA_URL = 'https://a2.techbuzz360.com/demanzo/wp-content/uploads/';
export const ARTICLE_URLS = 'https://demanzo.com/wp-json/wp/v2/';
export const BLOGS = 'https://demanzo.com/wp-json/custom/v1/post_details';
// export const BLOGS = 'https://a2.techbuzz360.com/demanzo/wp-json/custom/v1/blog/details';
export const SOURCE_BASE_URL = 'https://demanzo.com';